config/routes.rb
Rails.application.routes.draw do

  resources :sessions

  resources :users

  resources :notes

  resources :sequences

  root 'sequences#index'

  get 'practice/:id' => 'sequences#practice'

  post 'practice/:id/start' => 'sequences#start_practice'

  post 'compose/:id/start' => 'sequences#start_compose'

  get 'compose/:id' => 'sequences#compose'

  post 'compose/send/:id' => 'sequences#compose_receive'

  get 'serial/' => 'sequences#serial'

end

app/models/sequence.rb
class Sequence < ActiveRecord::Base
  has_many :notes
  has_many :sessions

  attr_accessor :input

  mount_uploader :file, FileUploader

  def create_notes
    self.notes.each do |n|
      n.destroy
    end

    mapping = {35 => 7, 36 => 7, 38 => 5, 40 => 5, 42 => 1, 44 => 1, 46 => 1, 49 => 0, 57 => 0, 52 => 0,
               55 => 0, 51 => 2, 53 => 2, 59 => 2, 41 => 6, 43 => 6, 45 => 6, 47 => 4, 48 => 3, 50 => 3 }

    # open sequence
    note_sequence = []
    info_array = []
    seq = MIDI::Sequence.new()

    File.open(File.join(Rails.root, 'public', self.file.to_s), 'rb') { |f|
      seq.read(f)
    }

    # get notes and time signature
    seq.tracks.each do |t|
      info_array.concat t.events.select {|e| e.class == MIDI::NoteOn}
      if t.events.select {|e| e.class == MIDI::TimeSig}.any?
        self.meter_top = t.events.select {|e| e.class == MIDI::TimeSig}.first.data[0]
        self.meter_bottom = 2**t.events.select {|e| e.class == MIDI::TimeSig}.first.data[1]
      end
    end

    info_array.each do |n|
      note_drum = mapping[n.note]
      note_duration = (n.off.time_from_start - n.time_from_start) / seq.ppqn.to_f * (self.meter_bottom / 4.to_f)

      note_bar = ((n.time_from_start / seq.ppqn.to_f) * (self.meter_bottom / 4.to_f) / self.meter_top).floor
      note_beat = (n.time_from_start / seq.ppqn.to_f) * (self.meter_bottom / 4.to_f) % self.meter_top

      new_note = Note.create(:drum => note_drum, :duration => note_duration.round(2), :bar => note_bar, :beat => note_beat, :sequence_id => self.id)

      note_sequence.push(new_note)
    end

    self.bars = self.notes.select(:bar).distinct.length
    self.save

    return note_sequence
  end

  # outputs notes for vexflow format
  def vexflow
    bars = []
    self.bars.times do |i|
      # assume 3 voices max
      voices = []
      voice1 = []
      voice2 = []
      voice3 = []

      # buffer for excess notes
      overflow1 = []
      overflow2 = []

      # voice1
      self.notes.where(:bar => i).select('beat, duration').distinct.order('beat ASC').each do |n|
        if !voice1.empty?
          if voice1.last[0].end_beat < n.beat # fill in gap
            # voice1 << [{:duration => n.beat - voice1.last[0].end_beat, :drum => -1}]
            voice1.last.each do |m|
              m.assign_attributes({ :duration => n.beat - m.beat })
            end
          elsif voice1.last[0].end_beat > n.beat # overlap
            overflow_notes << n
            next
          end
        else # leading rest
          if n.beat != 0
            voice1 << [{:duration => n.beat, :drum => -1}]
          end
        end
        voice1 << self.notes.where(:bar => i, :beat => n.beat, :duration => n.duration)
      end

      # overflow => voice2
      overflow1.each do |n|
        if !voice2.empty?
          if voice2.last[0].end_beat < n.beat # fill in gap
            # voice2 << [{:duration => n.beat - voice2.last[0].end_beat, :drum => -1}]
            voice2.last.each do |m|
              m.assign_attributes({ :duration => n.beat - m.beat })
            end
          elsif voice2.last[0].end_beat > n.beat # overlap
            overflow2 << n
            next
          end
        else # leading rest
          if n.beat != 0
            voice2 << [{:duration => n.beat, :drum => -1}]
          end
        end
        voice2 << self.notes.where(:bar => i, :beat => n.beat, :duration => n.duration)
      end

      # overflow2 => voice3
      overflow2.each do |n|
        if !voice3.empty?
          if voice3.last[0].end_beat < n.beat # fill in gap
            # voice3 << [{:duration => n.beat - voice3.last[0].end_beat, :drum => -1}]
            voice3.last.each do |m|
              m.assign_attributes({ :duration => n.beat - m.beat })
            end
          elsif voice3.last[0].end_beat > n.beat # overlap
            overflow2 << n
            next
          end
        else # leading rest
          if n.beat != 0
            voice3 << [{:duration => n.beat, :drum => -1}]
          end
        end
        voice3 << self.notes.where(:bar => i, :beat => n.beat, :duration => n.duration)
      end

      # add trailing rests
      if voice1.any? && voice1.last[0].end_beat != self.meter_bottom
        extraRests = []
        voice1.last.each do |m|
          if self.meter_bottom - m.beat > 1
            m.assign_attributes({ :duration => 1 })
            extraRests[0] = {:duration => self.meter_bottom - m.end_beat, :drum => -1}
          else
            m.assign_attributes({ :duration => self.meter_bottom - m.beat })
          end
        end
        if extraRests.any?
          voice1 << extraRests
        end
        # voice1 << [{:duration => self.meter_bottom - voice1.last[0].end_beat, :drum => -1}]
      end
      if voice2.any? && voice2.last[0].end_beat != self.meter_bottom
        extraRests = []
        voice2.last.each do |m|
          if self.meter_bottom - m.beat > 1
            m.assign_attributes({ :duration => 1 })
            extraRests[0] = {:duration => self.meter_bottom - m.end_beat, :drum => -1}
          else
            m.assign_attributes({ :duration => self.meter_bottom - m.beat })
          end
        end
        if extraRests.any?
          voice2 << extraRests
        end
        # voice2 << [{:duration => self.meter_bottom - voice2.last[0].end_beat, :drum => -1}]
      end
      if voice3.any? && voice3.last[0].end_beat != self.meter_bottom
        extraRests = []
        voice3.last.each do |m|
          if self.meter_bottom - m.beat > 1
            m.assign_attributes({ :duration => 1 })
            extraRests = {:duration => self.meter_bottom - m.end_beat, :drum => -1}
          else
            m.assign_attributes({ :duration => self.meter_bottom - m.beat })
          end
        end
        if extraRests.any?
          voice3 << extraRests
        end
        # voice3 << [{:duration => self.meter_bottom - voice3.last[0].end_beat, :drum => -1}]
      end

      # full measure rest
      if voice1.empty?
        voice1 << [{:duration => self.meter_bottom, :drum => -1}]
      end

      # add any voices to bar
      voices << voice1
      if voice2.any?
        voices << voice2
      end
      if voice3.any?
        voices << voice3
      end
      bars << voices
    end

    return bars
  end

  # def start_seq(mode, action, bpm)
  def start_seq(mode, bpm, sticking)
    new_session = Session.create(:sequence_id => self.id, :user_id => 1)

    if (mode == 5) # compose
      track1 = '[t:-1]'
      track2 = '[t:-1]'
      track3 = '[t:-1]'
      lengths = '[l:-1]'
      metadata = '[m:5,1,0]'
    else
      seq_length = self.notes.select('bar, beat').distinct.length

      # create tracks/lengths
      beats = []
      track1 = '[t:'
      track2 = '[t:'
      track3 = '[t:'
      lengths = '[l:'

      self.notes.select('bar, beat').distinct.each do |s|
        beats << self.notes.where(:bar => s.bar, :beat => s.beat)
      end

      if self.notes.first.hand.nil?
        for i in 0..(beats.length - 1)
          to_add = beats[i]

          (3 - beats[i].length).times do
            to_add << nil
          end

          if !to_add[0].nil?
            track1 << to_add[0].drum.to_s << ','
          else
            track1 << '-1,'
          end
          if !to_add[1].nil?
            track2 << to_add[1].drum.to_s << ','
          else
            track2 << '-1,'
          end
          if !to_add[2].nil?
            track3 << to_add[2].drum.to_s << ','
          else
            track3 << '-1,'
          end

          note1 = beats[i].first
          lengths << (note1.start.to_f / bpm * 60000).to_i.to_s << ','

          if i != beats.length - 1
            note2 = beats[i+1].first

            # add a rest to fill the gap between
            if beats[i+1].any? && note1.start + note1.duration < note2.start
              lengths << ((note1.start + note1.duration).to_f / bpm * 60000).to_i.to_s << ','
              track1 << '-1,'
              track2 << '-1,'
              track3 << '-1,'
            end
          end
        end
      end

      # else
      #   for i in 0..seq_length - 1
      #     if beats[i].where(:hand => 'left').any?
      #       track1 << beats[i].where(:hand => 'left').drum.to_s << ','
      #     else
      #       track1 << '-1,'
      #     end

      #     if beats[i].where(:hand => 'right').any?
      #       track2 << beats[i].where(:hand => 'right').drum.to_s << ','
      #     else
      #       track2 << '-1,'
      #     end

      #     if beats[i].where(:hand => 'foot').any?
      #       track1 << beats[i].where(:hand => 'foot').drum.to_s << ','
      #     else
      #       track3 << '-1,'
      #     end

      #     if i == beats.length - 1
      #       lengths << beats[i].first.duration.to_s << ','
      #     else
      #       note1 = beats[i].first
      #       note2 = beats[i+1].first

      #       if beats[i+1].empty?
      #         lengths << note1.duration.to_s << ','
      #       elsif note1.start + note1.duration >= note2.start
      #         # truncate the note at the start of the next note
      #         lengths << (note2.start - note1.start).to_s << ','
      #       else
      #         # add a rest to fill the gap
      #         lengths << beats[i].first.duration.to_s << ',' << (note2.start - (note1.start + note1.duration)).to_s << ','
      #         track1 << '-1,'
      #         track2 << '-1,'
      #         track3 << '-1,'
      #       end
      #     end
      #   end
      # end

      metadata = '[m:' << mode.to_s << ',' << track1.count(',').to_s << ',' << sticking.to_s << ']'

      track1[-1], track2[-1], track3[-1], lengths[-1] = ']', ']', ']', ']'
      # lengths = '[l:' << ([1]*track1.count(',')).to_s.gsub!(/\s+/,'')[1..-1]
    end
    seq = [metadata, track1, track2, track3, lengths]

    puts seq

    # write sequence to serial

    sp = SerialPort.new('/dev/tty.usbmodem586841', 115200, 8, 1, SerialPort::NONE)
    sp.sync = true

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  include ActionController::Live
  before_action :set_sequence, only: [:show, :edit, :update, :destroy, :practice, :start_practice, :compose, :compose_receive, :start_compose]

  # GET /sequences
  # GET /sequences.json
  def index
    @sequences = Sequence.all
    @sequence = Sequence.new # for add form
  end

  # GET /sequences/1
  # GET /sequences/1.json
  def show
  end

  # GET /sequences/new
  def new
    @sequence = Sequence.new
  end

  # GET /sequences/1/edit
  def edit
  end

  # POST /sequences
  # POST /sequences.json
  def create
    @sequence = Sequence.new(sequence_params)

    respond_to do |format|
      if @sequence.save
        if not @sequence.bpm
          @sequence.create_notes
          format.html { redirect_to action: 'index', notice: 'Sequence was successfully created.' }
          format.json { render :index, status: :created, location: @sequence }
        else
          format.html { redirect_to action: 'compose', id: @sequence.id, notice: 'Sequence ready to compose.' }
          format.json { render :compose, status: :created, location: @sequence }
        end
      else
        format.html { render :new }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sequences/1
  # PATCH/PUT /sequences/1.json
  def update
    respond_to do |format|
      if @sequence.update(sequence_params)
        format.html { redirect_to @sequence, notice: 'Sequence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sequence }
      else
        format.html { render :edit }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sequences/1
  # DELETE /sequences/1.json
  def destroy
    notes = @sequence.notes
    @sequence.destroy
    respond_to do |format|
      format.html { redirect_to sequences_url, notice: 'Sequence was successfully destroyed.' }
      format.json { head :no_content }
      notes.each do |n|
        n.destroy
      end
    end
  end

  # GET /sequences/1
  # GET /sequences/1.json
  def practice
  end

  def start_practice
    if params[:demoMode]
      mode = 0 #DEMO mode
    elsif params[:enableStepByStep] and not params[:enableLoop]
      mode = 1  #STEP BY STEP
    elsif not params[:enableLoop]
      mode = 2 #PRACTICE
    elsif params[:enableLoop] and params[:enableStepByStep]
      mode = 3 #STEP BY STEP LOOP
    elsif params[:enableLoop]
      mode = 4 #PRACTICE LOOP
    end
    puts "MODE:**********", mode

    if params[:enableSticking]
      sticking = 1
    else
      sticking = 0
    end

    @sequence.start_seq(mode, params[:playBPM].to_i, sticking)  #@sequence.bpm) cant use this until high speed lights issue fixed
    render :nothing => true
  end

  def compose
  end

  def start_compose
    @sequence.start_seq(5,1,0);
    render :nothing => true
  end

  def compose_receive
    @sequence = Sequence.find_by_id(params[:id])

    @sequence.notes.each do |n|
      n.destroy
    end
    notes = []

    hits = params[:hits]
    hits.each do |hit|
      total_beat = (@sequence.bpm*hit[:start].to_i/60000).round(2)
      puts "total_beat****#{total_beat}"
      note_bar = (total_beat/@sequence.meter_bottom)
      note_beat = total_beat % @sequence.meter_bottom
      notes << Note.create(:drum => hit[:drum], :bar => note_bar, :beat => note_beat, :sequence_id => @sequence.id, :duration => 0.25)
    end

    @sequence.end_compose()
    render :nothing => true
  end

  # GET /serial
  def serial
    response.headers['Content-Type'] = 'text/event-stream'

    redis = Redis.new
    redis.subscribe('messages.create') do |on|
      on.message do |event, data|
        response.stream.write("data: #{data}\n\n")
      end
    end
  rescue IOError
  ensure
    redis.quit
    response.stream.close
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sequence
      @sequence = Sequence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sequence_params
      params.require(:sequence).permit(:title, :artist, :default_bpm, :meter_top, :meter_bottom, :bars, :file)
    end
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/views/sequences/_form.html.erb
<%= simple_form_for @sequence, html: { class: 'form-horizontal' }, defaults: { wrapper_html: { class: 'form-group' } } do |f| %>
  <%= f.input :title, input_html: { class: 'form-control' }, required: true %>
  <%= f.input :artist, input_html: { class: 'form-control' }, required: true %>
  <%= f.input :file, required: true %>
  <%= f.button :submit %>
<% end %>

app/views/sequences/_form2.html.erb
<%= simple_form_for @sequence, html: { class: 'form-horizontal' }, defaults: { wrapper_html: { class: 'form-group' } } do |f| %>
  <%= f.input :title, input_html: { class: 'form-control' }, required: true %>
  <%= f.input :artist, input_html: { class: 'form-control' }, required: true %>
  <%= f.input :bpm, input_html: { class: 'form-control form-num-input bpm-input' }, required: true %>
  <%= f.input :meter_top, input_html: { class: 'form-control form-num-input' }, required: true %>
  <%= f.input :meter_bottom, input_html: { class: 'form-control form-num-input' }, required: true %>
  <%= f.button :submit %>
<% end %>

app/views/sequences/compose.html.erb
<% content_for :title, "Compose" %>

<%= javascript_tag "var sequence = #{@sequence.to_json}" %>

<button class="start-compose-btn" id="start-compose-btn"><i class="fa fa-circle"></i></button>
<button class="stop-compose-btn hidden" id="stop-compose-btn"><i class="fa fa-stop"></i></button>

<div class="compose-timer">BAR <span>0001</span> &emsp;&emsp; BEAT <span>0</span></div>

<button class="play-compose-btn" id="play-compose-btn" disabled>Demo track</button>

<script>
  var hits = [];
  $("#start-compose-btn").click(function(e) {
    console.log("start");
    var id = sequence.id;
    $.post('/compose/'+id+'/start', function(data) {});
    var hitSource = new EventSource("/serial");
    hitSource.onmessage = function(e) {
      var hit = jQuery.parseJSON (e.data);
      console.log(hit);
      hits.push(hit);
    }
    $(this).addClass('hidden');
    $("#stop-compose-btn").removeClass('hidden');
  });

  // hit form: [h:4,23643,1]
  $("#stop-compose-btn").click(function(e) {
    $("#play-compose-btn").removeAttr("disabled");
    console.log("hit button");
    // hits.push("[h:4,23643,1]"); // for testing
    if (hits.length != 0) {
      $.ajax({
        type : "POST",
        url :  '/compose/send/' + sequence.id,
        dataType: 'json',
        contentType: 'application/json',
        data : JSON.stringify( {"hits" : hits} )
      });
    }
    $(this).addClass('hidden');
    $("#start-compose-btn").removeClass('hidden');
  });

  $("#play-compose-btn").click(function(e) {
    // window.location.href = "/practice/" + sequence.id;
    $.ajax({
      type : "POST",
      url :  '/practice/' + sequence.id + '/start',
      dataType: 'json',
      contentType: 'application/json',
      data : JSON.stringify( {
        demoMode: true,
        playBPM: sequence.bpm,
        enableLoop: false,
        enableStepByStep: false,
        enableSticking: false
      })
    });
  });

    // hitSource.onopen = function (e) {
    //   console.log("OPEN state \n"+e.data);
    // };

    // hitSource.onmessage = function(e) {
    //   var hit = jQuery.parseJSON( e.data );
    //   console.log(hit.drum);

      // TODO: start time needs to accurately correlate to bar/beat in sequence
      // TODO: support for checking if both notes at same time are hit
    //   if (hit.drum == drawSequence.notes[hit.start].drum) {
    //     console.log("HIT");
    //     stepSequence();
    //   }
    // };

    // hitSource.onerror = function (e) {
    //    console.log("Error State  \n\n"+e.data);
    // };
  // }

  var audioContext = new AudioContext();
  var isPlaying = false;
  var startTime;
  var current16thNote;

  var lookahead = 25.0;
  var scheduleAheadTime = 0.1;
  var nextNoteTime = 0.0;
  var noteResolution = 2;
  var noteLength = 0.075;
  var notesInQueue = [];
  var seqIn16thNotes = [];
  var timerWorker = new Worker("../assets/metronomeworker.js");

  timerWorker.onmessage = function(e) {
    if (e.data == "tick") {
      scheduler();
    }
    else
      console.log("message: " + e.data);
  };
  timerWorker.postMessage({"interval":lookahead});

  // advance current note and time by a 16th note
  function nextNote() {
    var secondsPerBeat = 60.0 / songSettings.bpm;
    nextNoteTime += 0.25 * secondsPerBeat;
    current16thNote++;
  }

  // push note onto the queue
  function scheduleNote(beatNumber, time) {
    // create an oscillator
    var osc = audioContext.createOscillator();
    osc.frequency.value = 500;

    if (beatNumber == sequence.bars * 16)
      return; // don't play the last note in a sequence
    if (beatNumber == -28 || beatNumber == -20) // count in - audio only TODO: visuals
      return;
    if ((noteResolution == 1) && (beatNumber % 2))
      return; // don't play 16th notes
    if ((noteResolution == 2) && (beatNumber % 4))
      return; // don't play 8th notes

    if (beatNumber > -1) {
      $('.compose-timer span').last().text(parseInt($('.compose-timer span').last()) + 1 + '');
      if (beatNumber % 16 == 0) {
        osc.frequency.value = 750;
      }
      notesInQueue.push({ note: beatNumber, time: time });
    }

    osc.connect(audioContext.destination);
    osc.start(time);
    osc.stop(time + noteLength);
  }

  // schedule notes and advance pointer
  function scheduler() {
    while (nextNoteTime < audioContext.currentTime + scheduleAheadTime) {
      scheduleNote(current16thNote, nextNoteTime);
      nextNote();
    }
  }

  // toggle play/stop
  function play() {
    isPlaying = !isPlaying;
    if (isPlaying) { // start playing
      if (!songSettings.stepByStep)
      // current16thNote = -32 * sequence.meter_top/sequence.meter_bottom;
      current16thNote = 0;
      nextNoteTime = audioContext.currentTime;
      timerWorker.postMessage("start");
      return "stop";
    }
    else {
      timerWorker.postMessage("stop");
      return "play";
    }
  }
</script>

app/views/sequences/edit.html.erb
<h1>Editing sequence</h1>

<%= render 'form' %>

<%= link_to 'Show', @sequence %> |
<%= link_to 'Back', sequences_path %>

app/views/sequences/index.html.erb
<% content_for :title, "Library" %>

<table class="table table-striped table-hover tablesorter" id="library">
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Date Added</th>
      <th>Last Played</th>
      <th>Top Score</th>
    </tr>
  </thead>

  <tbody>
    <% @sequences.each do |sequence| %>
      <tr data-link="<%= sequence.id %>">
        <td><%= sequence.title %></td>
        <td><%= sequence.artist %></td>
        <td data-text="<%= sequence.created_at %>"><%= sequence.created_at.strftime('%a %b %d') %></td>
        <% if sequence.sessions.empty? %>
          <td data-text="1940-07-07">n/a</td>
          <td>0%</td>
        <% else %>
          <td data-text="<%= sequence.sessions.last.created_at %>"><%= time_ago_in_words(sequence.sessions.last.created_at) %> ago</td>
          <td><%= sequence.sessions.maximum(:score) %>%</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>  

<div class="modal fade add-song" tabindex="-1" role="dialog" aria-labelledby="addSongLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <h2>Import song</h2>
      <%= render 'form' %>
      <hr>
      <h2>Record song</h2>
      <%= render 'form2' %>
    </div>
  </div>
</div>

app/views/sequences/new.html.erb
<h1>New sequence</h1>

<%= render 'form' %>

<%= link_to 'Back', sequences_path %>

app/views/sequences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sequence.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @sequence.artist %>
</p>

<p>
  <strong>BPM:</strong>
  <%= @sequence.bpm %>
</p>

<p>
  <strong>Meter top:</strong>
  <%= @sequence.meter_top %>
</p>

<p>
  <strong>Meter bottom:</strong>
  <%= @sequence.meter_bottom %>
</p>  

<%= link_to 'Edit', edit_sequence_path(@sequence) %> |
<%= link_to 'Back', sequences_path %>